version: '3.8'

services:
  api:
    container_name: teddy-api
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.api
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - api-network

  db:
    container_name: teddy-api-db
    image: postgres:15.4-alpine
    restart: on-failure
    ports:
      - "5432:5232"
    volumes:
      - ./src/app/database/setup.sql:/docker-entrypoint-initdb.d/dbinit.sql
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - .env.database
    networks:
      - api-network

volumes:
  db-data:

networks:
  api-network:
    driver: bridge